apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sampleapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/emmanuelokpatuma/Argocdtask
    targetRevision: master
    path: sampleapp
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
